export const CREATE = 'Create'
export const UPDATE = 'Update'
export const EDIT = 'Edit'
export const CREATEAGENT = 'Create Agent'
export const EDITAGENT = 'Edit Agent'
export const SIGNIN = 'Log in'
export const ONLINE = 'Online'
export const OFFLINE = 'Offline'
export const DEFAULTAVATAR = 'https://github.com/shadcn.png'

